### PR TITLE
Add full profile on 7.x-1.12 directory

### PR DESCRIPTION
**Pull request by FrancescJR**
I am not sure where I should have added the profile. 7.x-1.10 and 7.x-1.12.5 look like they have the "old" japanese_dkan without the latest changes. I put everything in a new created directory called 7.x-1.12. I am not sure if this is the desired, if not, no problem,  please tell me and I will follow your instructions!

Thanks!

### CODE REVIEW

**Comment by sawanoboly** [comment]
Ah, I used `7.x-1.12.5` directory because I can't recognize that there are difference of install steps between 7.x-1.12 〜 7.x-1.12.y in the future.

Can we kept using same profile while version less than 7.x-1.13 ? how do you think ?

**Comment by FrancescJR** [comment]
Yes, it sounds good. Therefore, should I replace the 7.x-1.12.5 profile for the profile that has all the proper changes?

**Comment by sawanoboly** [comment]
Yes, please. 👍

**Comment by FrancescJR** [comment]
All right, you can can cancel this PR, I am going to make a different one with a single commit with all the changes.

**Comment by sawanoboly** [comment]
close by #6

**Pull request closed without merging**
