### PR TITLE
For version 1.12

### PR DESCRIPTION
**Pull request by FrancescJR**
Hi,
This are the changes for version DKAN 7.12. There are mainly new strings, that's all. There is only one doubt:
-first comit, I am getting DKAN from github - instead of copying the DKAN from the files found in localhost. The reason for that is that with DKAN version 1.12 there is no "build.make" file. Should be no problem, but maybe you want to do it in a different way.
Regards!
Cesc

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks !

I'll update both of normal DKAN and Japanese DKAN.

**Comment by sawanoboly** [comment]
@FrancescJR 

Hi, 

I've found one problem.

The japanese_dkan profile depends on `dkan_sitewide_profile_page`. But it was already removed from core since 7.x-1.12.

https://github.com/NuCivic/dkan_sitewide_profile_page

It must be installed ? Or, could we remove from depends ?

**Comment by sawanoboly** [comment]
FYI.

I've copied from github to continue installing like below.

```
git clone https://github.com/NuCivic/dkan_sitewide_profile_page.git /var/www/html/profiles/dkan/modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page
```

**Comment by FrancescJR** [comment]
Sorry, my bad!

There is no need to add this module. The module is not needed anymore and will not be used. I just forgot to delete the dependency on the Japanese DKAN profile.

I want to do a new PR with this fix, it looks like I can only ask for PR for master branch. Is that OK?

**Comment by sawanoboly** [comment]
@FrancescJR 
Yes, please send to master branch. Thanks,

**Pull request merged**
